Still work in progress, just some vague notes and thoughts


* Problem
Photo/video ("media") management software is a bit of a mess.

For example, in Digikam, depending on settings, certain metadata is written into Digikam's database, and other metadata ends up in photo/video EXIF (and other types of metadata).
The process isn't very transparent, and it's possible that your photos end up with metadata you don't want there, or vice versa, the software erases or mangles tags you don't expect to be touched.

Media galleries are a mess as well.

Depending on the gallery software, different tags are supported, even for basic properties like media creation time.
So something that works in one gallery may not work in another, which locks you in and makes it harder to switch (or even evaluate different software).

Some galleries like Google Photos don't support updating photo metadata once you've uploaded them.
So you really want to get the metadata right before uploading, unless you're a fan of manually deleting and reuploading again.

* Solution (?)
This tool aims to do few things:

- keep track of media metadata in an sqlite database.

  From time to time you 'import' new metadata into the database and in case there were any changes you are presented with a diff. This gives you a chance to restore photos from a backup if you see any unexpeted changes.

- check that media has reasonable metadata

  - proper creation date
  - timezone information (since usually datetime stored in photo is local time)
  - GPS coordinates

  It doesn't feel as much to ask, does it?
  Yet, it can be surprisingly tedious to ensure, especially if your photos were collected over years from different cameras/phones; send to you by friends by social media, etc.

- in case some metadata above is missing, the tool tries its best to offer you an automatic fix via =exiftool=

  The metadata database mentioned above gives you additional reassurance that the tool won't mess up your media files.


* Typical issues with metadata

Here's an incomplete list of issues I noticed on my media files that the tool detects or aims to fix

- some photos had =24= as an "hour" field in the creation date

- sometimes =GPSDateTime= included =Z= at the end of timestamp, which will be a parsing error in most software

- some photos only have =ModifyDate= instead of =CreateDate= or =CreationDate=

  in this case the tool suggests you to fill =CreationDate= from other tags or infer from the filename

- some photos don't have any proper datetime tags at all

  in this case the tool tries to extract it from the filename or =GPSDateTime=

- media shared via social media has creation date tags zeroed out (i.e. =0000-00-00 00:00:00=) and has no coordinates

- some media is randomly missing =GPSPosition=, e.g. if you were on the tube/plane, or just GPS didn't wake up in time

- most cameras/phones don't set =OffsetTimeOriginal= (timezone information)

  in this case the tool tries to infer it from creation (local) time and GPS coordinates

- Digikam version 7 (Ubuntu 22.04) sometimes was stripping =GPSDatetime= from photos while editing unrelated metadata

  TODO need to file a bug

- Digikam version 8 with =exiftool= backend sometimes erases XMP tags [[https://bugs.kde.org/show_bug.cgi?id=473826]]
